apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privileged-app
  template:
    metadata:
      labels:
        app: privileged-app
    spec:
      containers:
        - name: privileged-container
          image: nginx:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 80
